"""projects and dependencies

Revision ID: 0d6f4908ff04
Revises: 43c9f0a95612
Create Date: 2026-08-10 15:28:11.677386

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d6f4908ff04"
down_revision: Union[str, Sequence[str], None] = "43c9f0a95612"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column(
            "last_scanned_at", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", name="uq_projects_url"),
    )
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("ecosystem", sa.String(length=50), nullable=False),
        sa.Column("package_name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=True),
        sa.Column("purl", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "ecosystem",
            "package_name",
            "version",
            name="uq_dependency_project_pkg_version",
        ),
    )
    op.create_index(
        "ix_dependencies_ecosystem_package",
        "dependencies",
        ["ecosystem", "package_name"],
        unique=False,
    )
    # NOTE: autogenerate wanted to drop ix_advisories_embedding_hnsw here — that's a FALSE
    # POSITIVE. The HNSW index is created via raw SQL in migration 43c9f0a95612 and isn't
    # declared on the model, so alembic can't see it and assumes it's stray. Removed so we
    # do NOT drop our vector index.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dependencies_ecosystem_package", table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_table("projects")
    # ### end Alembic commands ###
