"""advisories and affected

Revision ID: 6ec38f936a6a
Revises: 08577a05374d
Create Date: 2026-07-29 17:17:13.873980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ec38f936a6a'
down_revision: Union[str, Sequence[str], None] = '08577a05374d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cvss_vector', sa.Text(), nullable=True),
    sa.Column('epss_score', sa.Numeric(), nullable=True),
    sa.Column('cwes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('withdrawn_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_advisories_source_id')
    )
    op.create_table('affected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisory_id', sa.Integer(), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('package_name', sa.Text(), nullable=False),
    sa.Column('vulnerable_range', sa.Text(), nullable=True),
    sa.Column('fixed_version', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisory_id', 'ecosystem', 'package_name', 'vulnerable_range', name='uq_affected_advisory_pkg_range')
    )
    op.create_index('ix_affected_ecosystem_package', 'affected', ['ecosystem', 'package_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_affected_ecosystem_package', table_name='affected')
    op.drop_table('affected')
    op.drop_table('advisories')
    # ### end Alembic commands ###
